server:
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
      port-header: X-Forwarded-Port
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 5120MB
      max-request-size: 5120MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zcmu?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 510105xzyf
  #    url: jdbc:mysql://1.117.180.56:3307/gims?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
  #    username: root
  #    password: 2298246596lucy
  banner:
    location: /config/banner.txt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: 127.0.0.1 # redis 服务 ip
    port: 6379 # 端口
    database: 0 # 默认数据库索引
    password: # redis 密码
    timeout: 1000 # 连接超时
    jedis:
      pool:
        max_idle: 130 # 连接池最大空闲数
        min_idle: 10 # 连接池最小空闲数
        max_wait: 1000 # 最长等待时间
        jmx_name_prefix: jedisPool
  mvc:
    async:
      request-timeout: 1800000

zcmu:
  constant:
    user_pic_url: https://zcmu-resours-1305805121.cos.ap-shanghai.myqcloud.com/dev/zcmu/caoshen.png
    lesson_pic_url: https://zcmu-resours-1305805121.cos.ap-shanghai.myqcloud.com/dev/zcmu/caoshen.png
    auth_head: Authorization
    default_password: 123456
  jwt:
    config:
      key: nQ4apIwm0EDAFWqrZkXutM1y7b3TUo28 # token 加密密钥
      ttl: 5
  aes:
    key:
      keyRoom: b>Tl95^wWK}!iGQcD6Ip(<NmrXn:"3_$sxCj0%vZqF#@t2oY|MU*P1)L4?dg&7eBJ8SEVHh{ua~RkfAyzO+
  weChat:
    config:
      appId:
      appSecret:
  #  sms:
  #    config:
  #      appId:
  #      appKey:
  #      smsSign: # 签名
  #  smtp:
  #    config:
  #      fromEmail: # 发件人邮箱
  #      authCode: # 发件人邮箱授权码
  #      host: smtp.163.com # SMTP 域名
  #      port: 25 # 邮件发送端口
  #  webRootUrl: http://:8080/#/ # 前端网页根 url
  #  defaulHeadUrl: #默认头像
  tecent:
    cos:
      file_host: /dev/zcmu/
      bucket_name: zcmu-resours-${zcmu.tecent.cos.config.app_id}
      endpoint: ${zcmu.tecent.cos.bucket_name}.cos.${zcmu.tecent.cos.config.region}.myqcloud.com
      config:
        region: ap-shanghai
        app_id: 1305805121
        secret_id: AKIDztfFoBNPEqJbh1EOROJD9FG6tYDj1JVa
        secret_key: 72qWAg6LNCuX6axDTegbR8h7MTS3VyHR
        bucket_name: ${zcmu.tecent.cos.bucket_name}
  trash:
    price:
      bottle: 5
      paper: 2
      other: 1
  max_temp: 70

